### ISSUE TITLE
Misleading sort property in README

### ISSUE THREAD

**Issue by emoriarty** [orbit-love/notion-ruby-client#28]
Hello,

I've remarked that in the [query a database](https://github.com/orbit-love/notion-ruby-client#query-a-database) section in the README it is used the `sort` property but is not actually correct after the Notion API upgrade. Now it used the plural form for that property: `sorts`.

I've found this change when updating to notion-ruby-client 1.0.0. When using the `sort` property the following error was raised.
```sh
body failed validation: body.sort should be not present, instead was `{"timestamp":"created_time","direction":"descending"}`.  (Notion::Api::Errors::NotionError)
```
It was fixed by changing to `sorts`.

Probably, it would be a good idea to update the example at [query a database](https://github.com/orbit-love/notion-ruby-client#query-a-database).

**Comment by phacks** [comment]
Great catch @emoriarty, I must have missed that breaking change from their changelog. Would you be interested in opening a PR?

**Comment by emoriarty** [comment]
Done! #29 
I've also taken the liberty to replace the property with the timestamp `created_time`. Let me know if it works for you.

**Comment by phacks** [comment]
Thanks a lot for your contribution!
