### ISSUE TITLE
Problems with SSL and Faraday

### ISSUE THREAD

**Issue by evsasse** [orbit-love/notion-ruby-client#31]
I was having problems with SSL and Faraday. And managed to solve it. Documenting it here, because I imagine that other people will look for an issue here if they face a similar problem.

Recently updated my stack on Heroku to Ubuntu 22, and that brings in OpenSSL 3.

This lib uses the Faraday gem under the hood, and Faraday got a bit lost after this was updated ☝️. I had a few other libs installed that have also broken in similar fashion.

https://github.com/lostisland/faraday/wiki/Setting-up-SSL-certificates#ubuntu
On their wiki, they suggest passing down a `ca_path` or `ca_file`.

You can set that up on your `Notion.configure` block. Follow the instructions on the Faraday wiki to figure out the path of the certificate file on your system. Mine ended up looking like this:
```ruby
Notion.configure do |config|
  ...
  config.ca_file = "/usr/lib/ssl/certs/ca-certificates.crt"
end
```

---

On the Faraday wiki they also suggest setting up the `SSL_CERT_FILE` env variable. I've tried that, but it didn't seem to fix it 🤷.

**Comment by phacks** [comment]
Thank you so much for taking the time to document your solution! I’m sure it’ll be helpful to many others. I’m going to close the issue as it doesn’t require any further action—if you think there is something more to be done, feel free to reply and we’ll reopen it!

**Comment by drnic** [comment]
Thanks for this.

In my app I added:

```ruby
Rails.application.config.to_prepare do
  ... other stuff...

  # Heroku path to certs
  if File.exist?("/usr/lib/ssl/certs/ca-certificates.crt")
    Notion.configure do |config|
      config.ca_file = "/usr/lib/ssl/certs/ca-certificates.crt"
    end
  end
end
```

**Comment by Clemalfroy** [comment]
Faraday::SSLError (SSL_CTX_load_verify_file: system lib)

Just writing down the error I had for SEO as it took me a long time to find the solution

Thanks for the solution 🙏
