### ISSUE TITLE
How to add member

### ISSUE THREAD

**Issue by sai1024** [orbit-love/notion-ruby-client#35]
hi, i want to use api add member, control to permission, how to do, thanks.

**Comment by sai1024** [comment]
Does Notion has an API method to add access to a new user?

I'm building a content service. Users pay for it in Telegram with a subscription feature. Now those, who bought subscription get access to content in Notion. So, basically I'm looking for a method, that adds/revoke user's access from Notion's page.

Is there any?

**Comment by phacks** [comment]
Hi @sai1024! Unfortunately, this doesn’t seem to be possible with the current Notion API. The only two methods they offer are to [retrieve a user](https://developers.notion.com/reference/get-user) or [get a list of all users](https://developers.notion.com/reference/get-users)—nothing about updating permissions or creating users.

I would suggest joining the [Notion Developers Slack community](https://join.slack.com/t/notiondevs/shared_invite/zt-1cnw5dx1f-KXwfmxRDZW8gnf9jDyW_AA) to pass them your feature request. In the meantime, I’m going to close this issue as there is nothing we can do in the context of this repository until they create the relevant endpoints.

**Comment by sai1024** [comment]
ok, thanks.

**Comment by sai1024** [comment]
> 你好@sai1024！不幸的是，当前的 Notion API 似乎无法做到这一点。他们提供的唯一两种方法是[检索用户](https://developers.notion.com/reference/get-user)或[获取所有用户的列表——与](https://developers.notion.com/reference/get-users)更新权限或创建用户无关。
> 
> 我建议加入[Notion Developers Slack 社区](https://join.slack.com/t/notiondevs/shared_invite/zt-1cnw5dx1f-KXwfmxRDZW8gnf9jDyW_AA)，向他们传递您的功能请求。与此同时，我将关闭这个问题，因为在他们创建相关端点之前，我们在这个存储库的上下文中无能为力。

hi,  sorry, slack link is no longer active is dead, can you give me a new?

**Comment by sai1024** [comment]
"To join this workspace, you’ll need to ask the person who originally invited you for a new link."
