### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by tobinharris** [orbit-love/notion-ruby-client#8]
Hi 

Thanks for making this client, it's great!

Do you have any plans to add search?

**Comment by phacks** [comment]
Hi! Thanks for opening the issue. PR #12 will be shipped soon and will add support for `/search`!

We might wait until we have all other endpoints that Notion added recently before we release a new version (`0.1.0`), but I anticipate those to land in the coming week.

**Comment by phacks** [comment]
@tobinharris If it helps, the Search endpoint is available in the `0.1.0-beta1` prerelease if you want to try it out! https://rubygems.org/gems/notion-ruby-client/versions/0.1.0.pre.beta1
